---

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Unarchive packer
  unarchive:
    src: "{{ packer_download_url }}"
    dest: "{{ packer_executable_directory }}"
    remote_src: true
    mode: 0755
    creates: "{{ packer_executable_directory }}/packer"
