---
- name: Update cache in zenial
  apt:
    update_cache: yes
  when: ansible_distribution_release == "xenial"

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Unarchive packer
  unarchive:
    src: "{{ download_url }}"
    dest: /usr/local/bin
    remote_src: yes
