---
- name: Update cache in zenial
  apt:
    update_cache: yes
  when: distribution_release == "xenial"

- name: Install unzip
  package:
    name: unzip
    state: present

- name: Download checksum file
  get_url:
    url: "{{ checksum_url }}"
    dest: "{{ checksum_file_location }}"

- name: Slurp in checksum file
  slurp:
    src: "{{ checksum_file_location }}"
  register: checksum_file

- name: Download the packer binary
  get_url:
    url: "{{ download_url }}"
    dest: "{{ download_file_location }}"
    checksum: "{{ checksum }}"

- name: Unarchive packer
  unarchive:
    src: "{{ download_file_location }}"
    dest: /usr/local/bin
    remote_src: yes

- name: Cleanup download and checksum
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ checksum_file_location }}"
    - "{{ download_file_location }}"
