---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos7
    image: centos:7
  - name: bionic
    image: ubuntu:18.04
  - name: centos8
    image: centos:8
  - name: focal
    image: ubuntu:20.04
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
